---
# handlers file for docker
  - name: Restart {{jenkins_container_name}} container
    systemd:
      state: restarted
      enabled: yes
      daemon_reload: yes
      name: "{{ jenkins_container_name }}"
